name: E2E Tests

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        description: "Environment to run tests against"
        default: "https://react-storefront-e2e.vercel.app/"
        type: choice
        options:
          - https://staging-demo.saleor.io/
          - https://demo.saleor.io/
          - https://react-storefront-e2e.vercel.app/
      api:
        required: true
        description: "API to run tests against"
        default: "https://storefront-automation.staging.saleor.cloud/graphql/"
        type: choice
        options:
          - https://staging-demo.saleor.io/graphql/
          - https://demo.saleor.io/graphql/
          - https://storefront-automation.staging.saleor.cloud/graphql/

  schedule:
    - cron: "00 2 * * 1-5"

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2
        with:
          version: 7.11.0 # version used by Vercel
      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "pnpm"

      - name: Get env
        id: get-env-uri
        env:
          DEFAULT_ENV_URI: "https://react-storefront-e2e.vercel.app/"
        run: |
          echo "ENV_URI=${{ github.event.inputs.environment || env.DEFAULT_ENV_URI }}" >> $GITHUB_OUTPUT

      - name: Get API
        id: get-api-url
        env:
          DEFAULT_API_URL: "https://storefront-automation.staging.saleor.cloud/graphql/"
        run: |
          echo "SALEOR_API_URL=${{ github.event.inputs.api || env.DEFAULT_API_URL }}" >> $GITHUB_OUTPUT

      - name: Cypress run on demo
        uses: cypress-io/github-action@v4
        with:
          record: true
          config: baseUrl=${{ steps.get-env-uri.outputs.ENV_URI }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SALEOR_API_URL: ${{ steps.get-api-url.outputs.SALEOR_API_URL }}
          CYPRESS_USER_EMAIL: "admin@example.com"
          CYPRESS_USER_PASSWORD: "admin"
          CYPRESS_DIGITAL_PRODUCT: "cloud"
          CYPRESS_WITHOUT_VARIANTS: "beanie"
          CYPRESS_WITH_VARIANTS: "zoom"
          CYPRESS_PRODUCT_TO_SEARCH: "polo"
